### ISSUE TITLE
Change manual offsets to dynamic ones based on device screen

### ISSUE THREAD

**Issue by TheOdd** [TheOdd/http-codes#2]
As stated in the title, I'd like to have the offsets for the application be based on the device's screen dimensions rather than a hard-coded magic number. This would allow for a better viewing experience in general across all devices. Contributions are welcome and I can provide clarification if needed.

**Comment by TheOdd** [comment]
For example, commit 7256565d315061e36cf4cb84a08bd1d436fa012d is not ideal for centering the content in the web application, as it only really looks okay on a few screen dimensions and nothing else.

**Comment by nmkettler** [comment]
@TheOdd I can take this if you want. I can also remove the inline styling and separate it out to.

**Comment by TheOdd** [comment]
@nmkettler That would be fantastic! Let me know if you need any more info on it.

**Comment by nmkettler** [comment]
@TheOdd It should be responsive now <a href="https://github.com/TheOdd/http-codes/pull/3">#3</a>. I can also start cleaning up the code. Specifically some of the components.

**Comment by TheOdd** [comment]
@nmkettler Sounds good. I looked over your PR and only found a small thing that you might need to look at, but other than that it looks good. It'd be great if you could start the code cleanup if you want, too.

**Comment by TheOdd** [comment]
@nmkettler Alright, the PR is now merged. Thanks for contributing.
